stages:
    - build
    - deploy

include:
  - project: 'deploy/common-cicd'
    file: '/common-project.yml'
    ref: 'main'

docker-build:
    rules:
      - if: '$CI_COMMIT_BRANCH == "main"'
        variables:
          DOCKER_BUILD_ARGS: --build-arg NPM_BUILD_SCRIPT=build:production
      - if: '$CI_COMMIT_BRANCH == "dev"'
        variables:
          DOCKER_BUILD_ARGS: --build-arg NPM_BUILD_SCRIPT=build:development
    extends: .docker-service-build
    after_script:
      - docker stop ${CI_PROJECT_NAME}-${ENVIRONMENT_CODE} || true
      - docker run -d --hostname ${CI_PROJECT_NAME} --rm --network ${ENVIRONMENT_CODE} --name ${CI_PROJECT_NAME}-${ENVIRONMENT_CODE} ${CI_REGISTRY_IMAGE}:${ENVIRONMENT_CODE}
      -  docker exec -it webserver ahp dev.alageum.kz iam-frontend-dev "/" http://iam-frontend-dev/
