stages:
    - build
    - deploy

include:
  - project: 'deploy/common-cicd'
    file: '/common-project.yml'
    ref: 'main'

docker-build:
    extends: .docker-service-build
    rules:
      - if: '$ENVIRONMENT_CODE  == "dev"'
        variables:
          DOCKER_BUILD_ARGS: --build-arg NPM_BUILD_SCRIPT=build:production
      - if: '$ENVIRONMENT_CODE  == "dev"'
        variables:
          DOCKER_BUILD_ARGS: --build-arg NPM_BUILD_SCRIPT=build:development
    after_script:
      - echo DEV http://${CI_PROJECT_NAME}-${ENVIRONMENT_CODE}
      - docker exec -i webserver ahp ${DOMAIN} ${CI_PROJECT_NAME}-${ENVIRONMENT_CODE} "/" http://${CI_PROJECT_NAME}-${ENVIRONMENT_CODE}/
