export enum MainActionTypes {
    SET_TOKEN = "SET_TOKEN",
    SET_USER_SELECTED_KEY = "SET_USER_SELECTED_KEY",
    SET_CURRENT_USER_DATA_ITEM_INFO = "SET_CURRENT_USER_DATA_ITEM_INFO",
    SET_CURRENT_OPENED_MENU = "SET_CURRENT_OPENED_MENU",
    SET_DICTIONARY_TAB_ACTIVE_KEY = "SET_DICTIONARY_TAB_ACTIVE_KEY"
}
