export enum MainActionTypes {
    SET_TOKEN = "SET_TOKEN",
    SET_USER_SELECTED_KEY = "SET_USER_SELECTED_KEY",
    SET_CURRENT_USER_FIO = "SET_CURRENT_USER_FIO",
    SET_CURRENT_USER_DATA_ITEM_INFO = "SET_CURRENT_USER_DATA_ITEM_INFO",
    SET_CURRENT_LAYOUT_MENU = "SET_CURRENT_LAYOUT_MENU",
    SET_CURRENT_OPENED_MENU = "SET_CURRENT_OPENED_MENU",
    SET_DICTIONARY_TAB_ACTIVE_KEY = "SET_DICTIONARY_TAB_ACTIVE_KEY",
    SET_MODAL_VARIABLE_SALARY = "SET_MODAL_VARIABLE_SALARY",
    SET_MODAL_CONSTANT_SALARY = "SET_MODAL_CONSTANT_SALARY",
    SET_SELECTED_CONTRACT_TYPE = "SET_SELECTED_CONTRACT_TYPE",
    SET_SUB_CONTRACT_INITIAL_DIVISION = "SET_SUB_CONTRACT_INITIAL_DIVISION",
    SET_SUB_CONTRACT_DIVISION_ID = "SET_SUB_CONTRACT_DIVISION_ID",
    SET_MODAL_SUB_CONTRACT_LAYOUT = "SET_MODAL_CONTRACT_LAYOUT",
    SET_SIMPLE_ADD_MODAL_SUB_CONTRACT_LAYOUT = "SET_SIMPLE_ADD_MODAL_CONTRACT_LAYOUT",
    SET_ADD_REQ_SELECT_FIELDS = "SET_ADD_REQ_SELECT_FIELDS"
}
